# ===================================================================
# Spring Boot configuration.
#
# This configuration will be overriden by the Spring profile you use,
# for example application-dev.yml if you use the "dev" profile.
# ===================================================================

# ===================================================================
# Standard Spring Boot && Cloud properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================
info:
    build:
        name: ${rootProject.name}
        description: ${description}
        version: ${version}
        time: ${(new Date()).getTime()}
        number: ${rootProject.swissVersioning.getProps().getProperty('build_number')}
    pid : \${PID}
server:
    port: 0
    max-http-header-size: 65536

management:
    context-path: '/manage'

spring:
    application:
        index: \${random.int}
    metrics:
        servo:
            enabled: false
    sleuth:
        sampler:
            percentage: 0.1
    cloud:
        consul:
            host: localhost
            port: 8500
            discovery:
                healthCheckPath: \${management.context-path}/health
                management-suffix: manage
    mvc:
        favicon:
            enabled: false

endpoints:
    shutdown:
        enabled: true
    health:
        sensitive: false

hystrix:
    threadpool:
        addDataPointThreadPool:
            coreSize : 30

# ===================================================================
# NB Hipster specific properties
# ===================================================================

swiss:
    async:
        corePoolSize: 2
        maxPoolSize: 50
        queueCapacity: 10000
    swagger:
        title: NBOCollectorService API
        description: NBOCollectorService API documentation
        version: 0.0.1
        termsOfServiceUrl:
        contact:
        license:
        licenseUrl:
        includePattern: "/api/.*"
#    cors: #By default CORS are not enabled. Uncomment to enable.
#        allowed-origins: "*"
#        allowed-methods: GET, PUT, POST, DELETE, OPTIONS
#        allowed-headers: "*"
#        exposed-headers:
#        allow-credentials: true
#        max-age: 1800

